<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <RootNamespace></RootNamespace>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FFF.Player\FFF.Player.vbproj" />
    <None Update="Fixtures\sample.ass" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
